---
driver:
  name: terraform
  root_module_directory: test/fixtures/tf_module
  parallelism: 4

provisioner:
  name: terraform

verifier:
  name: terraform
  systems:
    - name: default
      backend: gcp
      controls:
        - gcp-compute
        - gcp-firewall
        - gcp-network
        - gke-cluster
platforms:
  - name: terraform

suites:
  - name: kt_suite
    verifier:
      inspec_tests:
        - test/integration/kt_suite